# Generated by Django 2.1.2 on 2018-10-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('plan_createTime', models.DateTimeField()),
                ('plan_startDate', models.DateTimeField()),
                ('plan_endDate', models.DateTimeField()),
                ('plan_share', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planItem_date', models.DateTimeField()),
                ('planItem_type', models.CharField(max_length=20)),
                ('planItem_json', models.TextField()),
                ('planItem_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelService.TravelPlan')),
            ],
        ),
        migrations.CreateModel(
            name='TravelShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelService.TravelPlan')),
            ],
        ),
        migrations.CreateModel(
            name='TravelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_phone', models.CharField(max_length=20, unique=True)),
                ('user_email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='travelshare',
            name='share_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravelService.TravelUser'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='plan_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TravelService.TravelUser'),
        ),
    ]
