# Generated by Django 2.1.2 on 2018-10-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplanitem',
            name='planItem_order',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelshare',
            name='share_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='plan_createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
