# Generated by Django 2.1.2 on 2018-10-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelService', '0002_auto_20181021_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveluser',
            name='user_wechat',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
