# Generated by Django 2.1.2 on 2018-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelService', '0003_traveluser_user_wechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveluser',
            name='user_email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='traveluser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='traveluser',
            name='user_wechat',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
