# Generated by Django 2.1.2 on 2018-10-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelService', '0005_auto_20181030_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveluser',
            name='user_email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='traveluser',
            name='user_phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='traveluser',
            name='user_wechat',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
